### ISSUE TITLE
when timeout, always retry

### ISSUE THREAD

**Issue by will0x0909** [BobTheBuidler/eth_retry#32]
`        while True:
            try:
                return await func(*args,**kwargs)  # type: ignore
            except asyncio.exceptions.TimeoutError as e:
                logger.warning(f'asyncio timeout [{failures}] {_get_caller_details_from_stack()}')
                if ENVS.ETH_RETRY_DEBUG:
                    logger.exception(e)
                continue
            except Exception as e:
                if not should_retry(e, failures):
                    raise
                if failures > ENVS.ETH_RETRY_SUPPRESS_LOGS:
                    logger.warning(f'{str(e)} [{failures}]')
                if ENVS.ETH_RETRY_DEBUG:
                    logger.exception(e)
            
            # Attempt failed, sleep time.
            failures += 1
            if ENVS.ETH_RETRY_DEBUG:
                logger.info(f'sleeping {round(failures * sleep_time, 2)} seconds.')
            await asyncio.sleep(failures * sleep_time)`
  when TimeoutError occured, will always retry without sleep, why?

**Comment by BobTheBuidler** [comment]
Closing this, the assumption is that a call that only failed due to Timeout does not need to be throttled and can immediately be retried (and typically succeed)

Feel free to reopen if you see an issue with this approach
